### ISSUE TITLE
web , 找不到 cocos2d-js.js

### ISSUE THREAD

**Issue by Wanderxx** [hyz1992/hyz-encript#1]
我这边构建后 是cocos2d-js-min.js
虽然我无 apply-web.js 更改了路径 但是 加密后 页面无法打开了
因为 替换代码 是基于 cocos2d-js 的，这个文件被min后 替换代码就失效了

**Comment by Wanderxx** [comment]
方便的话可以 qq交流 199101046

**Comment by hyz1992** [comment]
已经解决了
